title: "2 Young" # title, default to config.title
subtitle: "Example page to test the theme"  # subtitle, default to use config.subtitle
title_case: true
excerpt: false
word_count: true
favicon: "assets/favicon.ico"
manifest: #"assets/site.webmanifest"
direction: "ltr"
rss: "//blog.skk.moe/atom.xml"

author:
  enabled: true
  name: # default to config.author
  bio: "*A newbie learns to code.* __Lorem ipsum__ dolor sit amet, [consectetur adipiscing](//hexo.io) elit. Sed elit felis, placerat sit amet nisl eu, viverra posuere nisl. " # default to config.description
  avatar: "assets/avatar.jpg" # default to gravatar > assets/avatar.jpg

social:
  show_in_footer: true
  show_in_author_widget: true
  email: "mailto:liame@example.com"
  github: "//github.com/torvalds"
  stackoverflow: "//stackoverflow.com/u/22656"
  twitter: "//twitter.com/Twitter"
  facebook: "//facebook.com/facebook"
  instagram: "//instagram.com/natgeo"
  whatsapp: "//wa.me/3194657728"
  wechat: "//via.placeholder.com/200x200?text=WeChat+QR"
  qq: "//wpa.qq.com/msgrd?uin=1145141919"
  steam: "//steamcommunity.com/id/zenoxio"
  psn: "//psnprofiles.com/Hakoom"
  xbox: "//account.xbox.com/profile?gamertag=Xonatron"
  twitch: "//twitch.tv/20musiclive"
  youtube: "//www.youtube.com/channel/UCZCFT11CWBi3MHNlGf019nw"
  bilibili: "//space.bilibili.com/481701670"

style: "auto" # 'auto', 'light', 'dark'

light:
  theme_color: "#008e86"
  text_color: "#333"
  background_color: "#fff"
  header_image: "assets/header.jpg"
  header_css: "color:white!important;text-shadow:0 0 4px rgba(0,0,0,0.5);"
  footer_image: "assets/footer.jpg"
  footer_css: "color:white!important;"
  code_highlight_css: "//cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/styles/default.min.css" # set config.highlight.hljs to true

dark:
  theme_color: "#0ecfc5"
  text_color: "#ccc"
  background_color: "#222"
  header_image: "assets/header.jpg"
  header_css: "color:white!important;text-shadow:0 0 4px rgba(0,0,0,0.5);"
  footer_image: "assets/footer.jpg"
  footer_css: "color:white!important;"
  code_highlight_css: "//cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/styles/monokai.min.css" # set config.highlight.hljs to true

date_format:
  index: "YYYY-MM-DD"
  post: "MMM Do YYYY"

footer:
  md: "© 2016-2020 AuthorName Powered by [Hexo](//hexo.io)"
  text_align: "right"

paginator:
  hide_on_one_page: false
  show_in_post: true
  prev_text: "‹"
  next_text: "›"

back_to_top:
  enabled: true
  hide_timeout: 3000
  height_threshold: 500

style_toggle:
  enabled: true

nav:
  archives:
    enabled: true
    url: "archives/"
  categories:
    enabled: true
    url: "categories/"
  tags:
    enabled: true
    url: "tags/"
  about:
    enabled: true
    url: "about/"
  friends:
    enabled: true
    url: "friends/"

library:
  fontawesome: "//cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/js/all.min.js"
  jquery: "//cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"
  fancybox:
    enabled: true
    css: "//cdn.jsdelivr.net/gh/fancyapps/fancybox/dist/jquery.fancybox.min.css"
    js: "//cdn.jsdelivr.net/gh/fancyapps/fancybox/dist/jquery.fancybox.min.js"

tagcloud:
  enabled: true
  amount: # amount of tag to show, default is unlimited

toc:
  enabled: true

copyright: # display copyright info after post
  enabled: true
  license: '<a href="//creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>' # include "license: [html]" in the post header to overwrite

outdate_warning: # show warning if post older than specified days
  enabled: true # include "no_expiration: true" in the post header to disable for individual post
  days: "365"

comment:
  disqus: #"nobody-65534"

analytics:
  google: #"UA-000000-2"