archive: "archive"
category: "category"
tag: "tag"
friend: "friend"
about: "about"
prev_text: "prev"
next_text: "next"
home: "home"
word_count: "words"
outdated_warning: "This post is created %1$s, the content may be outdated. "
post_author: "author"
post_license: "license"
post_url: "link"